### ISSUE TITLE
Suggest tools and technologies

### ISSUE THREAD

**Issue by dileepadev-old** [foss-nibm/foss-nibm.github.io#4]
### Frontend tools

- HTML
- CSS
- JavaScript
- Tailwind
- React

**Comment by TharinduX** [comment]
- TypeScript
- React
- Strapi 
- Tailwind

**Comment by ChamiduChamodya** [comment]
**Technologies**

- TypeScript
- React
- Strapi
- Tailwind CSS
- Mongo DB
- Express JS
- Node

**Tools**

- VSCode/Intellij
- Postman

**Comment by dileepadev-old** [comment]
### Check polls:

- [Frontend tools for official website](https://github.com/orgs/nibmfossc/discussions/3)
- [Backend tools for official website](https://github.com/orgs/nibmfossc/discussions/4)
- [Dev tools for NIBM FOSS Community Website](https://github.com/orgs/nibmfossc/discussions/5)
